// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "CPAPlatform/internal/domain"
	dto "CPAPlatform/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// ConversionRepo is an autogenerated mock type for the conversionRepo type
type ConversionRepo struct {
	mock.Mock
}

type ConversionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *ConversionRepo) EXPECT() *ConversionRepo_Expecter {
	return &ConversionRepo_Expecter{mock: &_m.Mock}
}

// GetAllConversions provides a mock function with given fields: filter
func (_m *ConversionRepo) GetAllConversions(filter dto.ConversionFilter) []*domain.Conversion {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllConversions")
	}

	var r0 []*domain.Conversion
	if rf, ok := ret.Get(0).(func(dto.ConversionFilter) []*domain.Conversion); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Conversion)
		}
	}

	return r0
}

// ConversionRepo_GetAllConversions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllConversions'
type ConversionRepo_GetAllConversions_Call struct {
	*mock.Call
}

// GetAllConversions is a helper method to define mock.On call
//   - filter dto.ConversionFilter
func (_e *ConversionRepo_Expecter) GetAllConversions(filter interface{}) *ConversionRepo_GetAllConversions_Call {
	return &ConversionRepo_GetAllConversions_Call{Call: _e.mock.On("GetAllConversions", filter)}
}

func (_c *ConversionRepo_GetAllConversions_Call) Run(run func(filter dto.ConversionFilter)) *ConversionRepo_GetAllConversions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dto.ConversionFilter))
	})
	return _c
}

func (_c *ConversionRepo_GetAllConversions_Call) Return(_a0 []*domain.Conversion) *ConversionRepo_GetAllConversions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConversionRepo_GetAllConversions_Call) RunAndReturn(run func(dto.ConversionFilter) []*domain.Conversion) *ConversionRepo_GetAllConversions_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: conversion
func (_m *ConversionRepo) Save(conversion *domain.Conversion) *domain.Conversion {
	ret := _m.Called(conversion)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.Conversion
	if rf, ok := ret.Get(0).(func(*domain.Conversion) *domain.Conversion); ok {
		r0 = rf(conversion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conversion)
		}
	}

	return r0
}

// ConversionRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ConversionRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - conversion *domain.Conversion
func (_e *ConversionRepo_Expecter) Save(conversion interface{}) *ConversionRepo_Save_Call {
	return &ConversionRepo_Save_Call{Call: _e.mock.On("Save", conversion)}
}

func (_c *ConversionRepo_Save_Call) Run(run func(conversion *domain.Conversion)) *ConversionRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.Conversion))
	})
	return _c
}

func (_c *ConversionRepo_Save_Call) Return(_a0 *domain.Conversion) *ConversionRepo_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConversionRepo_Save_Call) RunAndReturn(run func(*domain.Conversion) *domain.Conversion) *ConversionRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewConversionRepo creates a new instance of ConversionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConversionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConversionRepo {
	mock := &ConversionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
